### ISSUE TITLE
Support Alpine Linux

### ISSUE THREAD

**Issue by marco-c** [mozilla/glean#1410] opened 2021-01-04 10:27 UTC
Currently, the released wheel is `glean_sdk-33.9.1-cp36-abi3-manylinux2014_x86_64.whl`.

**Comment by badboy** [comment] 2021-01-05 11:08
cc @mdboom 
I'm not entirely sure what we need to do. We're building this using Python 3.8, which is a still-supported version.
Do we also need to build with Python 3.9 to support that one?

**Comment by marco-c** [comment] 2021-01-05 12:02
>  I'm not entirely sure what we need to do. We're building this using Python 3.8, which is a still-supported version.

The only wheel you have is the one for 3.6, so anyone with a Python version other than 3.6 will have to build from source.

>  Do we also need to build with Python 3.9 to support that one?

For a Python library we have written in Rust, where we are using [maturin](https://github.com/PyO3/maturin), we simply build with [this PATH](https://github.com/mozilla/pyo3-parsepatch/blob/5592de516a90f91b5528f2216ac7cbcf6a1b5408/Dockerfile#L7) and maturin takes care of it for us. I'm not sure how you'd do it in your case.

**Comment by badboy** [comment] 2021-01-05 13:11
maturin looks interesting and might solve this for us too, but it requires some changes to our project first.

**Comment by mdboom** [comment] 2021-01-05 14:31
Because the wheel specifies `abi3`, the wheel works with any Python [supporting abi3](https://docs.python.org/3/c-api/stable.html), which is Python 3.2 and later.  

If I make a fresh environment with Python 3.9, for example, you can see it installs using the wheel:

```
$ python
Python 3.9.1 | packaged by conda-forge | (default, Dec 21 2020, 22:08:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

```
$ pip install glean_sdk
Collecting glean_sdk                                                                                                  
  Downloading glean_sdk-33.9.1-cp36-abi3-manylinux2014_x86_64.whl (1.6 MB)                                                 |████████████████████████████████| 1.6 MB 2.9 MB/s                        
```

There must be something else going on in the mozphab build linked [here](https://community-tc.services.mozilla.com/tasks/KTWAkCj8S-eBsfU82r7Ktw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKTWAkCj8S-eBsfU82r7Ktw%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log).  I'll see if I can reproduce.

**Comment by mdboom** [comment] 2021-01-05 15:06
I think we are running into this, and it's alpine-linux / musl specific: https://github.com/pypa/pip/issues/3969

I tried the suggested workaround [here](https://github.com/pypa/pip/issues/3969#issuecomment-247381915), and that didn't work for me, but that's a fairly old comment -- it's possible that just doesn't work anymore.

**Comment by mdboom** [comment] 2021-01-05 18:10
The wheels we currently ship are built against glibc, so don't work on Alpine Linux (even with the `gcompat` and other packages installed -- that stuff seems a little bit stale / unmaintained / not well supported in Alpine).

We can produce wheels for Alpine Linux / musl by using Rust's `x86_64-unknown-linux-musl` toolchain with `RUSTFLAGS="-C target-feature=-crt-static"`, building on Alpine Linux itself (thanks @badboy for the compiler flag to unblock this).  Unfortunately, these wheels aren't compatible with "regular" glibc-based Linuxes.  Python doesn't have any support for installing specific wheels based on the libc implementation in use (though there is a [long discussion about how that might play out](https://github.com/pypa/packaging-problems/issues/69)).  It's possible that if we ship musl wheels as `linux` and the existing glibc wheels as `manylinux2014`, the precedence rules in `pip` will do the right thing (installing the `linux` ones on Alpine and `manylinux` on the distros that are known to be `manylinux` compatible), but there's nothing defining how that behavior works AFAIK, so it could break in the future, even if it works now.

If that doesn't work, we could theoretically ship both builds of Glean in the same wheel and at runtime detect the correct `.so` to use.  That sure feels like a hack, though.

There are some shorter-term half-measures we could do, however:

1) We can improve the build so it doesn't break when building on a `musl` system. This will bring Alpine Linux in line with the other second tier platforms, like BSD, where Glean will install, but requires a working Rust compiler.

2) Maybe don't use Alpine Linux for now?

(( Note that behind glean, there is also the [cffi](https://cffi.readthedocs.io/en/latest/) package that doesn't have Alpine-compatible wheels.  There is a [Alpine package](https://pkgs.alpinelinux.org/package/edge/main/x86/py3-cffi) for it, but that installs into `/usr/lib`, not `/usr/local/lib` that the `python:alpine-3.x` docker images install Python into. ))

**Comment by marco-c** [comment] 2021-01-05 18:49
> Maybe don't use Alpine Linux for now?

This is what I'm going to do for the time being, I totally forgot we were using Alpine in that task.
If a Rust compiler is required, I'd rather just use a Debian-based image and avoid the runtime cost of installing the Rust compiler.

**Comment by badboy** [comment] 2021-01-13 15:37
Closing this as made it possible to at least build it on Alpine now.
Actually shipping releases prebuilt for these platforms will require more work.

**Closed by badboy** 2021-01-13 15:37 UTC
